TRUTH = (
   "Kapan Terakhir Kali Kamu Coli?",
   "Kapan terakhir kali kamu berbohong?",
   "Kapan terakhir kali kamu menangis?",
   "Kapan terakhir kali kamu kentut?",
   "Apa ketakutan terbesarmu?",
   "Apa fantasi terbesar atau terhanehmu?",
   "Apa hal yang membuatmu senang orangtuamu tidak mengetahuinya?",
   "Pernahkah kamu selingkuh?",
   "Apa hal terburuk yang pernah kamu lakukan?",
   "Apa rahasia yang tidak pernah kamu ceritakan kepada siapapun?",
   "Apakah kamu punya bakat terpendam?",
   "Siapa selebriti yang pertama kali bikin kamu naksir?",
   "Apa pendapatmu tentang perselingkuhan?",
   "Apa pengalaman intim terburuk yang pernah kamu alami?",
   "Apakah kamu pernah melanggar hukum?",
   "Apa hal paling memalukan yang pernah kamu lakukan? Kapan?",
   "Apa hal yang paling membuatmu merasa insecure?",
   "Kesalahan terburuk apa yang pernah kamu lakukan?",
   "Apa hal paling menjijikkan yang pernah kamu lakukan?",
   "Siapa orang yang paling ingin kamu cium di antara kita?",
   "Hal terburuk apa yang pernah dilakukan orang terhadapmu?",
   "Apa kebiasaan terburukmu?",
   "Hal terburuk apa yang pernah kamu katakan/lakukan terhadap orang lain?",
   "Apa penyesalan terburukmu?",
   "Kenapa kamu putus dengan mantan yang sebelumnya?",
   "Kalau kamu bisa jadi tidak terlihat, apa hal pertama yang akan kamu lakukan?",
   "Apa rahasia yang kamu sembunyikan dari orangtuamu?",
   "Siapa orang yang diam-diam kamu sukai?",
   "Siapa orang terakhir yang kamu kepoin di media sosial?",
   "Kalau ada jin yang memberikanmu tiga permohonan, apa yang kamu inginkan?",
   "Siapa orang di antara kita yang menurutmu bisa lolos dari kiamat zombie dan siapa yang akan mati duluan? Beri tahu alasannya!",
   "Apa tontonan favoritmu saat masih kecil?",
   "Siapa orang yang paling sering kamu chat?",
   "Apa kebohongan terbesar yang pernah kamu katakan kepada orangtuamu?",
   "Apa mimpi paling aneh yang pernah kamu alami?",
   "Ceritakan detail ciuman pertamamu…",
   "Kapan terakhir kali kamu ngompol?",
   "Menurutmu, hewan apa yang terlihat paling mirip denganmu?",
   "Di antara kita, siapa orang yang paling kamu suka dalam konteks romantis?",
   "Di antara kita, siapa orang yang menurutmu paling baik dan paling buruk sifatnya?",
   "Siapa mantan terindahmu?",
   "Siapa orang yang ingin kamu jadikan istri/suami?",
   "Apakah kamu pernah melakukan ghosting?",
   "Apa aib yang kamu sembunyikan dari kami?",
   "Berapa jumlah mantanmu?",
   "Apakah kamu sasimo?",
   "Apakah kamu bisa ngaceng?",
   "Pernah gak lg jalan sama pacar trus papasan sama mantan yang bikin kamu belum move on",
   "Apakah kamu pernah menjadi korban ghosting?",
   "Apakah kamu pernah mencuri uang ibu mu?",
   "What do you thing about him?",
   "Apakah Kamu suka aku?",
   "Kamu Sayang Aku gak?",
   "Udah berapa sabun yang kamu bolongin?",
   "first time ketemu orang di virtual siapa?",
   "Ss chat terakhir sama temen",
   "Kenapa bisa suka padahal belum ketemu?",
   "Rahasia yang belum kamu ceritain ke siapapun",
   "Apa pendapat mu mengenai perselingkuhan yang dilakukan seseorang?",
   "Hal apa yang paling membantu mu agar tidak insecure?",
   "Apa penyesalan terburuk?",
   "Sebutin hobi yang lo suka",
   "Sebutin tanggal bulan tahun lahir lo",
   "Apa yang paling bikin insecure",
   "Sebutin ekskul yang lo ikutin pas sekolah?",
   "Sebutin jabatan lo di kelas",
   "Kalo ada kegiatan atau organisasi lo pernah jadi apa?",
   "Kegiatan apa yang lo lakuin yang bisa ngehasilin duit pas sekolah",
   "Pernah ikut lomba di sekolah? Sebutin lomba apa",
   "Pernah ga sakit parah banget yang lo ga mau itu terjadi lagi, kalo pernah sebutin apa kenapa gimana?",
   "Sebutin nama panggilan lo di rumah, sekolah, atau diluar itu",
   "Ngapain main hp terus yang ngechat juga ga ada",
   "Apa masakan mama yang paling enak",
   "Apa arti nama lo",
   "Satu kata buat grup ini",
   "empat paling jauh yang pernah dikunjungi",
   "Pernah ngerokok?",
   "Satu kata yang menggambarkan keluarga lo",
   "Kenapa masih jomblo?",
   "Me time versi lo?",
   "Mending jomblo atau pacaran? Apa alasannya",
   "Pujian paling berkesan buat lo?",
   
)

DARE = (
    "Ambil nomor secara acak dari kontakmu, telepon dia, dan bilang Aku mencintaimu",
    "Oncam Sekarang",
    "Coba Coli Terus Oncam",
    "Ceritakan kepada semua orang kisah memalukan tentang dirimu",
    "Coba jilat sikumu",
    "Posting selfie tertua di ponsel Anda di Instagram Stories",
    "Ceritakan kisah paling menyedihkan yang kamu tahu",
    "Melolong seperti serigala selama dua menit",
    "Menari tanpa musik selama dua menit",
    "Tari tiang dengan tiang imajiner",
    "Biarkan orang lain menggelitikmu dan mencoba untuk tidak tertawa",
    "Masukkan makanan ringan ke dalam mulut Anda sekaligus sebanyak yang Anda bisa",
    "Kirim selfie terbaru Anda.",
    "Kirim selfie terjelekmu.",
    "Kirim tangkapan layar riwayat pencarian facebook Anda",
    "Kirim tangkapan layar galeri Anda.",
    "Kirim tangkapan layar kotak masuk messenger Anda",
    "Katakan sesuatu yang sangat intim.",
    "Kirim tangkapan layar kotak masuk twitter Anda",
    "Kirim tangkapan layar layar beranda Anda.",
    "Kirim cover lagu favoritmu. ",
    "Lakukan lelucon lirik pada seseorang dan kirimkan buktinya.",
    "Akui gebetanmu saat ini. ❤️",
    "Ungkapkan siapa cinta sejatimu.",
    "Kirim tangkapan layar galeri Anda.",
    "Jadikan foto gebetanmu sebagai dpmu.",
    "Sarankan saya lebih berani.",
    "Spill akun ig lo",
    "Ss grup di wa",
    "Ss rc telegram",
    "Vn nyanyi disini",
    "Gombalin orang random",
    "Spill pesan tersimpan di tele",
    "Send video tiktok lo",
    "Spill hasil gabut lo",
    "Ss log panggilan WhatsApp",
    "Spill chat pertama kalian kenal",
    "Spill ranking tertinggi di SD SMP SMA",
    "Kirim foto pake seragam sekolah",
    "Kirim vn terfavorit yang lo suka denger",
    "Spill ranking tertinggi di SD SMP SMA",
    "Kirim foto pake seragam sekolah",
    "Kirim vn terfavorit yang lo suka denger",
    "Baca bbrpa ayat Alquran pake vn",
    "Spill chat bareng ayah",
    "Deskripsikan semua pemain tod",
    "Spill foto ootd favorit lo",
    "Kirim foto lo di lapangan",
    "Pesan untuk para member disini", 
    "Spill foto raport",
    "Sambung lagu sama pemain",
    "Spill pemberian mantan",
    "Spill JJ favorit lo",

)

